plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "C:\\Users\\Vrutik Dholakia\\Desktop\\pre_screener_tool\\screener-portal-new\\build"
publishOrigin = "ui"
commandOrigin = "ui"
base = "C:\\Users\\Vrutik Dholakia\\Desktop\\pre_screener_tool\\screener-portal-new"
command = "npm run build"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]